#+TITLE: Band of Blades – The Road to Skydagger Keep

* Karakterer

** Legionen

*** Shreya

 + En av de Utvalgte

*** Arun

 + Doktor/lege

*** Maleksei

 + Kranglet med [[Theonin][Theonin]], som ble irritert.

*** Theonin

 + Fikk en kikkert av [[Topaz][Topaz]].
 + Irriterer seg over [[Maleksei][Maleksei]].

*** Topaz

 + Ga en kikkert til [[Theonin][Theonin]], et minne fra hjemlandet.

*** Rashu Pakshi

 + Kommandør

*** Mana

 + Kvartermester

*** Marskalk

 + Marskalk

*** Anton

 + Krøkiker

** Blighter

*** Doktoren

+ Det ryktes at [[Doktoren][Doktoren]] var en vandød som fant tilbake sitt intellekt
  og selv, etter å ha blitt vendt om. Doktoren er kjent for sine
  grusomme eksperimenter.

* Lokasjoner

** Tigeria

+ Elv
+ Legionen unnslapp de vandøde ved å sabotere en bro som gikk over
  elven.

* Økter

** 5. februar

 + Legionen krysset et stykke unna Karlsburg en bro.
 + Spesialister snek seg ned til broen med hensikt å sprenge broen og
   sinke de vandøde.
 + [[Arun][Arun]] valgte å krysse vannet, under broen.
 + Oppdraget var en suksess, men det var på hengende håret: [[Maleksei][Maleksei]],
   [[Arun][Arun]] og [[Topaz][Topaz]] Dancing Sky havnet i vannet med en rekke vandøde
   følgende etter.
 + [[Theonin][Theonin]] holdt seg et stykke unna, og holdt utkikk over hele
   området. Med en kikkert han fikk av [[Topaz][Topaz]] Dancing Sky fikk han sett
   at ladningen var klar, og gitt signal om at kysten var klar. Han løp
   så ned til broen, og fyrte av en pil mot en sårbar del. Pilen traff
   på mirakuløst vis direkte og fikk satt broen ut av spill.

** 19. mars

+ Legionen har befestet seg på østsiden av elva [[Tigeria][Tigeria]].
+ Alle venter spent på [[Shreya][Shreya]], som forsvant litt før spesialistene dro
  ut på sabotasjeoppdraget.
+ Soldatene er spente, tause og engstelige.
+ [[Shreya][Shreya]] synes plutselig, bærende på en bylt. [[Shreya][Shreya]] skuer på
  nybegynnerne med et blikk som en jeger. Responsen er ærefrykt,
  henførthet uforstand, sinne.
+ Det viser seg at [[Shreya][Shreya]] bærer på en av [[Blighter][Blighter]] kreaturer. En kråke
  -- [[Doktoren][Doktoren]]. Hun etterlater seg [[Doktoren][Doktorens]] levninger, og forlater
  dem.
+ [[Arun][Arun]] oppdager en sort vekst som siver inn i armen. Han sover, og
  drømmer om en hvit kråke som faller om. Det slutter å pirke i
  såret. Det viser seg å være [[Shreya][Shreyas]] gjerning som leger ham for
  korrupsjonen i armen.
+ Det blir fest. Mana kaller [[Arun][Arun]] for en helt, for dåden han gjorde
  under sabotasjen av broen over [[Tigeria][Tigeria]]. Aruns brukkede arm blir
  leget, på bekostning av Fred.
+ Legionen avanserer mot Vestfronten, hvor det brenner og det er
  rester av våpen og katapulter. Vestfronten fungerer som et godt sted
  å hvile før ferden går videre til Plainsworth.

** 9. april

+ Arun blir spurt om å bli med på oppdraget [[Grevinnen][Grevinnen]], og melder
  seg med én gang. Han blir fortalt at planen er å dra om et par timer.
+ Shreya har reist seg opp og stirrer ut mot horisonten, etter at
  oppdragene har blitt valgt ut. Hun sier, «nå». Arun, som ikke har
  klart å bli med i tide, velger å bli med på oppdraget [[Kråkens Rede][Kråkens Rede]] isteden.

** 16. april

** 23. april

+ En kveld oppdager Adisha Darhdi en lukt av de vandøde, og varsler
  vaktholdet om den potensielle trusselen. Legionen klarer ikke å
  respondere, og de blir overrumplet. Det bryter ut kamp.
+ Rahika Kapatia dør.
+ Torm Coolhand dør.
+ Graf Anton Senacci dør.
+ Det blir gravferd for de døde, hvor levningene blir samlet og brent
  i verdige omgivelser, men med få ressurser til å lage flotte
  likbål. Sang og musikk følger med.

** 7. mai

+ I et mer eller mindre falleferdig telt holder generalstaben
  møte. Marskalken, nybarbert som alltid, har innført en daglig sjekk
  av våpen.
+ Det blir bestemt at Grevinnen og to speidere -- Adisha Darhdi og
  Topaz Dancing Sky -- sendes ut på oppdrag.

* Oppdrag

** Grevinnen

+ [[Shreya][Shreya]]
+ [[Maleksei][Maleksei]] (Eirik)
+ [[Theonin][Theonin]] (Espen)
+ Ember Wolves (Thomas)
+ Shattered Lions (Mikke)

+ Oppdraget tar gruppen inn mot en landsby langs elven Tigeria,
  gjennom hovedsakelig skog og vegetasjon.
+ Gruppen nærmer seg landsbyen, og Shreya tar brått fingeren opp mot
  munnen og ser på Theonin. Det høres bjeff, men ikke hundeaktig --
  noe som virker menneskelig. Shreya mener at noen må lede dem unna,
  de har ikke tid til et slag her. Rekrutt Oxana Sanzavicha blir valgt
  ut.
+ Oxana skader seg og trekker frem blod, spytter opp i luften og
  prøver å lokke dem. Lyden av bjeff blir tydeligere, og det er klart
  at de nærmer seg raskt.
+ På en liten høyde oppdager Oxana at hun er omringet av mennesker,
  som alle står på på fire -- som dyr. De skriker, og Oxana faller
  ned, men tar tak i et tre på hengende håret.
+ Ember Wolves holder på å bryte rekkene, men Maleksei irettesetter
  dem med en tale. Oxana må ofres, uten at Ember Wolves får lov til å
  prøve å redde henne.
+ Gruppen ser så landsbyen, og Theonin bruker en kikkert til å se at
  noe er alvorlig galt med innbyggerne -- de er alle blitt
  gjennomboret av små, sylskarpe glassbiter.
+ Shreya feier vekk kommentarer om at det muligens er en felle, og
  hopper ned en høyde før hun beveger seg i retning landsbyen.
+ Maleksei har fått vite at gruppen _må_ redde Grevinnen, koste hva
  det koste vil. Blant de vandøde skal de se etter riddere, som holder
  Grevinnen. Shreya løper uforsvalig inn blant de vandøde.
+ Maleksei havner i skvis mellom en ridder i sort rustning, og
  vandøde, over elven midt i byen. Boran forsøker å få med seg resten
  av rekruttene i Ember Wolves, men blir fanget av en vandød med
  glasskniver boret inn i kroppen.
+ Boran, en rekrutt, forsøker å bevege resten av Ember Wolves til å
  komme Maleksei til unsetning. Talen faller ikke i smak, og mens
  Boran alene avanserer mot Maleksei blir han grepet fatt i av en
  vandød med glasskniver boret inn i kroppen. En av knivene stikker
  inn i leggen, og blod fosser ut. Boran, drevet til vanvidd av
  stress, mister fatningen og slår mot den vandøde, hjelpesløs. Han
  dør, omfavnet av den livsfarlige vandøde.
+ Oxana faller ned fra treet, men er på beina. Hun forsøker å forsvare
  seg fra de vandøde, men blir etterhvert overmannet, og dør. En
  sortkledd kvinne, bærende på en sort langbue, nærmer seg åstedet og
  ser ned på Oxanas rester. Hun setter foten ned på restene, og går
  videre.
+ Shreya sloss de udøde, og blir begravet i en masse udøde. Hun
  forsvinner inn i mengden, men sloss tydeligvis videre.
+ Maleksei møter den sorte ridderen, som forteller om Legionens
  håpløse situasjon. Det eneste, sier ridderen, er å sverge tro til de
  udøde. Maleksei angriper, og får dekningsild av Theonin. Han finter,
  og klarer å stikke sverdet inn i ansiktet til ridderen.
+ Resten av Ember Wolves tar til kamp og kjemper seg mot broen og
  Maleksei. Princep Anton Albrekt viser sin sanne karakter, og hogger
  ned de vandøde som står i veien. De kommer seg fram i sikkerhet.
+ Theonin får en død udød over seg, men kommer seg unna. Han går mot
  Shattered Lions, skyter i luften, og setter i gang med en tale for å
  oppmuntre til mot og handling. De løper mot broen, kommer også fram
  i sikkerhet.
+ Maleksei ser at de andre kommer, og presser mot to gjenværende
  riddere. Med dekningsild får Maleksei overmannet én av dem og kastet
  ham ned i elven, men stiller seg faretruende nær kanten av brua og i
  en dårlig posisjon. Broen er klarert, men Maleksei sitter i saksa.
+ Theonin fører an gruppene med rookies og kommanderer dem til å fyre
  av mot den gjenværende ridderen. Ridderen blir skutt, men uheldigvis
  skjer det samme med Maleksei -- han faller ned i elven.
+ Anton, Islanya og Scarlet speider etter Grevinnen, og Anton nærmest
  snubler inn en dør før han skriker høylydt -- han har åpenbart sett
  noe skrekkinngytende.
+ Maleksei kjemper i vannet, veid ned av rustningen han bærer. Gjennom
  strabaset kutter han seg opp og tar skade. Theonin haster ned i
  vannet og hjelper Maleksei, men hører brått skriket fra Anton.
+ Theonin og Anton går inn i bygningen, og de ser en gruppe mennesker
  som er hengt etter huden, nakne og blodige, fra taket. Én av dem er
  Grevinnen. Theonin forsøker å få et nærmere blikk på situasjonen,
  men blir overumplet av en ridder som angriper, fra siden innenfor
  inngangen.
+ Scarlet tar seg inn fra taket, og ser fra et galleri Grevinnen som
  henger fra lenker i taket. Gjennom en omfattende redningsaksjon
  klarer Scarlet å fire seg ned med et rep, får kontakt med Grevinnen
  og sammen klatre opp på galleriet. Vel oppe, dukker en ridder opp,
  og stikker med et sverd mot Scarlet. Grevinnen kvikner til, og
  dytter Scarlet vekk og ned fra galleriet igjen.
+ Theonin, i basketaket med ridderen oppdager at det kommer
  ytterligere enda en ridder. Han får bistand fra Islanya, og får
  anledning til å fyre av musketten på en slik måte at de
  uskadeliggjør begge ridderne.
+ Maleksei overvinner ridderen i vannet, og kommer seg til sikkerhet,
  tross store skader.
+ Scarlet klarer å skjære seg løs fra repet, og lander lett ned i
  første etasje av bygningen. Islanya og Anton løper frem og ser det
  som skjer med Scarlet. Islanya tar frem musketten og skyter mot
  ridderen som står oppe i galleriet. Scarlet, Islanya og Anton klarer
  å unnslippe ridderen og ta seg ut av bygningen.
+ Maleksei klarer å samle rookies til handling, og leder på nytt et
  tokt inn i taket og redder ut Grevinnen.
+ Sverenja Koveienicha av Shattered Lions blir hugget ned under
  flukten med Kontessa Hermina.
+ Shreya tar en pil i fart på vei mot Grevinnen, og den spidder
  hånden. Hun drar den ut, men konsekvensen er en sort vekst som
  vikler seg rundt armen, idet den slenger seg hit og dit utenfor
  Shreyas kontroll. Pilen ble skutt av den sortkledde jegeren.


** Kråkens Rede

+ [[Topaz][Topaz]]
+ [[Arun][Arun]]
+ Ghost Owls

+ Gruppen rir raskt mot målet, og setter fra seg hestene et stykke
  unna. De avanserer, men blir raskt overrumplet, hvorpå en soldat i
  Ghost Owls -- Gallant Rubin Garossi -- blir begravet under en bølge
  av vandøde.
+ Kråkens Rede er råttent, og omhyllet av en grågrønn tåke som beveger
  seg unaturlig mot vinden. Det skjer grusomme, industrielle prosesser
  mot offere: det kan se ut som de blir tvangsforet med et stoff som
  virker å være etsende.
+ Et stykke unna sentrum for disse prosessene kravler en person seg
  framover. Hun lider, og Arun kneler ved siden. Noe er alvorlig galt:
  magen buler ut, og kvinnen kaster opp en etsende masse som treffer
  Arun i siden. Smertene fortsetter, og Arun blir tvunget til å gjøre
  ende på kvinnen for å spare henne for videre elendighet.
+ Noen av veggene ser ut til å ha blitt etset vekk, og avslører for
  soldaten Aswina Kathri våpen og ei bok. Boka dokumenterer
  grusomme eksperimenter og forsøk, skrevet følelsesløst og
  systematisk. I margen står det ført ned notater, som åpenbart bærer
  sterke følelser. Notatene omhandler /Blighter/ -- Skjenderen -- og
  to andre som forfatteren ser ut til å ha brydd seg inderlig om. En
  datter og en ektemann. Ordet hevn er streket under mange ganger. Det
  som følger ordet «gjennombrudd» er: Skjenderen = Elenessa. Svakhet =
  Shreya.
+ Ivanka Ijaviecha bryter ut om Gallant Rubin at alt gir mening. Hun
  beskriver på en bisarr måte hvordan Rubin må være i live og valgte å
  sette seg i livsfare for Shreya. I hennes ord måtte Shreya ha et
  forsyn og en styrende hånd med på dette oppdraget, og gjort at
  resten overlevde. På ferden tilbake blir hun mer og mer distrahert,
  og bryter ut om umulige syner av Shreya. Når de slår leir foreslår
  Ivanka å ta første vakt. Underveis i vakta er det tydelig at Ivanka
  ser noe ute i skogen, og går vekk fra leiren. Hun kommer aldri
  tilbake.
+ På vei tilbake opplever de resterende, med tankene på Shreya, at
  armene nærmest er paralysert av kulde. Ikke før de når Legionen er
  kuldefornemmelsene over.


** Oppdraget for å hente inn Isfuglen (Kodenavn Isfugl)

+ Grevinnen
+ Arun Manabur
+ Topaz Dancing Sky
+ Ghost Owles

+ Arun Manabur får et sideoppdrag om å beskytte Grevinnen, men
  samtidig passe på at hun ikke har blitt et offer for korrupsjon
  under fangenskapet.
+ Gruppen marsjerer langs fjellinjen, og kommer etter 3 dager fram til
  en landsby i skogen. Tempelet ligger ved tvillingfossen, og fra den
  renner en elv gjennom landsbyen. Der ser gruppen noen landsbyboere
  forsøke å drukne noen i elven.
+ Tvillingfossen er en naturlig relikvie – noe som er igjen fra de
  utvalgte. De kjetterske innbyggerne har valgt å tilbe fossen som et
  naturlig fenomen, i strid med den rette tro og lære. «Drukningen» er
  en form for eksorsisme.
+ Rekrutten Elena råder Grevinnen til å gripe inn i situasjonen, og
  Grevinnen ser seg enig.
+ Eksorsismen fører til at personen dør, og blir holdt livløs oppe fra
  elven. Arun kaller det for hedensk aktivitet, og oppfordrer til å
  holde seg unna. Grevinnen mener at kjetteriet nettopp er en grunn
  til å nærme seg, for de må ledes til den rette tro.
+ Situasjonen eskalerer, og Grevinnen skyter med en signalpistol for å
  ta oppmerksomheten til landsbyboerne.
+ Landsbyboerne taler til Grevinnen, og sier at demonen kom til
  landsbyen for noen uker siden. Den fortalte mange vakre ord, og
  lovpriset den vakre fossen. Demonen søkte asyl i tempelet, men med
  oppholdet kom en forbannelse over landsbyen. En dag så de et lik ved
  fossen, og et lysglimt på toppen av høyden, som fra en rustning.
+ Arun og Elena forsøker å ta seg til elven, men landsbyen tillater
  bare Elena å nærme seg. Underveis mot liket oppdager Topaz Dancing
  Sky en vakt som sikter mot Elena med en børse.
+ Vakten har noe unaturlig som buler ut under armen. Han skyter, og
  lyden virker å være forsterket. Skuddet suser forbi Elena, som
  benytter anledningen til å løfte opp kroppen til den druknede
  kvinnen og løper mot Arun.
+ Arun og Elena gir livreddende hjelp, og klarer å redde henne fra
  drukningsdøden. En stor masse vann fra lungene kommer ut og treffer
  Arun, og kvinnen hoster så kraftig at tungen hennes er synlig. På
  tungen var det et øye. Kvinnen løper så vekk.
+ Etter å ha snakket med innbyggerne, lærer gruppen at vannet må ha
  blitt forgiftet, eller er besudlet på noen måte. Topaz Dancing Sky
  foreslår til en av innbyggerne at de bør bli med Legionen mot
  Skydagger Keep.
+ Gruppen begir seg opp en skjult sti, høyere opp fjellet. Der ser de
  Tempelet som er godt bygget; et gudommelig syn 
+ Topaz går først inn i tempelet og finner Isfuglen sittende på en 
  sirkulær platform foran fossen. Foran alteret finner de elvesteiner
  (slipte blokker) foran alteret man må hoppe over på. I tempelet er
  det ikke lett å se om gulvet, som er dekket av vann er et speilbilde
  eller fortsetter i evigheten nedover. Man kan se en sort skygge av
  et dyr som svømmer i vannet. Når man ser på den så forsvinner den.
+ Topaz blir truet av isfuglen idet hun kommer inn. "Hvis du fortsetter
  kan jeg ikke garantere at du er trygg". Sirkulær platform innerst ved
  fossen. Isfuglen sitter der. "Jeg vil ikke skade dere. Jeg råder
  dere til å trekke dere tilbake".
+ Contessa og Arun prøver å snakke Isfuglen ned fra å gjøre noe dumt og
  få han til å komme med dem tilbake til leiren. Topaz forsøker å komme
  seg over til isfuglen, men steinene han står på begynner å begeve seg.
+ Arun kaster seg ned i vannet for å forsøke å få oppmerksomheten til dyret
  i vannet. Får oppmerksomheten til noen mindre dyr og delvis til den store.
  Topaz kommer seg over og forsøker å få Isfuglen til å bli med tilbake til
  leiren. Isfuglen beveger handen til sliren sin nærmest automatisk, som
  en refleksiv handling.
+ Topaz holder frem et relikvie av (et gammelt kompass av en av oldtids profet)
  og viser det frem. Isfuglen ikke overbevist av relikviet og griper tak i Topaz.
  Det synes to arr på armen til Isfuglen som åpner seg som munner og begynner
  å bite etter Topaz. Arun skyter varselsskudd over hodet til Isfuglen og 
  formaner ham til å snakke med Contessaen. Cue flashback.
+ I en flashback så viser det seg at Contessa og Isfuglen har en bakgrunn som går
  åresvis tilbake. Det blir kjent at isfuglen egentlig heter VOYIS KARIYEVICH.
  Contessaen har rekvirert tjenestene til legionen og contessaen
  har brukt sine betydlige midler til å betale dem. De møtes på en bro utenfor
  Karlsburg etter Isfuglen og legionen har hamlet opp med en gruppe banditter
  De drikker vin sammen. Contessaen har vært fascinert av Isfuglen, hvordan han
  oppfører seg annerledes fra resten av offiserene og hvordan han har vært i ilden
  tidligere.
  Isfuglen lurer på hva de gjør, om de går rundt og leker imperiet. Maten de
  spiser kan jo mate mange familier. Contessaen overtaler Isfuglen til at han
  allerede har hjulpet mange familier ved å stoppe disse banditten.
  Contessaen får Isfuglen til å love at dagen han henger opp sverdet skal han komme
  og finne henne og jobbe for legionen.
  Ser noe som gløder faretruende rødt på horisonten. Askekongen har kommet.
+ Tilbake i tempelet så roper Contessa ut fornavnet til Isfuglen for å få han
  ut av transen og bryte gjennom korrupsjonen til menneskligheten hans. Navnet
  runger gjennom tempelet og stirrer på Contessa. Voyis husker plutselig
  contessaen og "Husker du hva du lovet meg? Du lovet du skulle bli med oss".
+ Voyis erindrer at en av landsbyboerene hadde blitt bitt og søkt til tempelet
  for å dø. Isfuglen drakk blodet hennes. Askekongens korrupsjon går dypt i
  sjelen til Voyis. Contessa overtaler allikevel Voyis til å ofre seg. Voyis
  kaster seg ned i vannet for å hente Topaz som har falt uti.
+ Arun ber Elena av Ghost Owls kutte bort dyrene som sitter i huden hennes. 
  Kuttet går ganske dypt og Arun får et kutt i pulsåren.
+ Topaz befinner seg under vann og kjemper mot en fisk. Klarer å drepe den og
  blir dratt til overflaten av Voyis. Arun kaster seg over Voyis og dekker 
  korrupsjonen på kroppen til Voyis med noen filler fra en av de falne
  utvalgte fra slaget ved Aldermark og heller tonic over såret. Korrupsjonen
  løftes fra Voyis og han blir bært tilbake til leiren.


** Garossi Herregård (Operasjon Huspass)

+ Adisha Darhdi
+ Maleksei
+ Shattered Lions
