#+TITLE: Band of Blades – The Road to Skydagger Keep

* Karakterer

** Legionen

*** Shreya

 + En av de Utvalgte

*** Arun

 + Doktor/lege

*** Maleksei

 + Kranglet med [[Theonin][Theonin]], som ble irritert.

*** Theonin

 + Fikk en kikkert av [[Topaz][Topaz]].
 + Irriterer seg over [[Maleksei][Maleksei]].

*** Topaz

 + Ga en kikkert til [[Theonin][Theonin]], et minne fra hjemlandet.

*** Rashu Pakshi

 + Kommandør

*** Mana

 + Kvartermester

*** Marskalk

 + Marskalk

*** Anton

 + Krøkiker

** Blighter

*** Doktoren

+ Det ryktes at [[Doktoren][Doktoren]] var en vandød som fant tilbake sitt intellekt
  og selv, etter å ha blitt vendt om. Doktoren er kjent for sine
  grusomme eksperimenter.

* Lokasjoner

** Tigeria

+ Elv
+ Legionen unnslapp de vandøde ved å sabotere en bro som gikk over
  elven.

* Økter

** 5. februar

 + Legionen krysset et stykke unna Karlsburg en bro.
 + Spesialister snek seg ned til broen med hensikt å sprenge broen og
   sinke de vandøde.
 + [[Arun][Arun]] valgte å krysse vannet, under broen.
 + Oppdraget var en suksess, men det var på hengende håret: [[Maleksei][Maleksei]],
   [[Arun][Arun]] og [[Topaz][Topaz]] Dancing Sky havnet i vannet med en rekke vandøde
   følgende etter.
 + [[Theonin][Theonin]] holdt seg et stykke unna, og holdt utkikk over hele
   området. Med en kikkert han fikk av [[Topaz][Topaz]] Dancing Sky fikk han sett
   at ladningen var klar, og gitt signal om at kysten var klar. Han løp
   så ned til broen, og fyrte av en pil mot en sårbar del. Pilen traff
   på mirakuløst vis direkte og fikk satt broen ut av spill.

** 19. mars

+ Legionen har befestet seg på østsiden av elva [[Tigeria][Tigeria]].
+ Alle venter spent på [[Shreya][Shreya]], som forsvant litt før spesialistene dro
  ut på sabotasjeoppdraget.
+ Soldatene er spente, tause og engstelige.
+ [[Shreya][Shreya]] synes plutselig, bærende på en bylt. [[Shreya][Shreya]] skuer på
  nybegynnerne med et blikk som en jeger. Responsen er ærefrykt,
  henførthet uforstand, sinne.
+ Det viser seg at [[Shreya][Shreya]] bærer på en av [[Blighter][Blighter]] kreaturer. En kråke
  -- [[Doktoren][Doktoren]]. Hun etterlater seg [[Doktoren][Doktorens]] levninger, og forlater
  dem.
+ [[Arun][Arun]] oppdager en sort vekst som siver inn i armen. Han sover, og
  drømmer om en hvit kråke som faller om. Det slutter å pirke i
  såret. Det viser seg å være [[Shreya][Shreyas]] gjerning som leger ham for
  korrupsjonen i armen.
+ Det blir fest. Mana kaller [[Arun][Arun]] for en helt, for dåden han gjorde
  under sabotasjen av broen over [[Tigeria][Tigeria]]. Aruns brukkede arm blir
  leget, på bekostning av Fred.
+ Legionen avanserer mot Vestfronten, hvor det brenner og det er
  rester av våpen og katapulter. Vestfronten fungerer som et godt sted
  å hvile før ferden går videre til Plainsworth.

** 9. april

+ Arun blir spurt om å bli med på oppdraget [[Grevinnen][Grevinnen]], og melder
  seg med én gang. Han blir fortalt at planen er å dra om et par timer.
+ Shreya har reist seg opp og stirrer ut mot horisonten, etter at
  oppdragene har blitt valgt ut. Hun sier, «nå». Arun, som ikke har
  klart å bli med i tide, velger å bli med på oppdraget [[Kråkens Rede][Kråkens Rede]] isteden.

** 16. april


* Oppdrag

** Grevinnen

+ [[Shreya][Shreya]]
+ [[Maleksei][Maleksei]] (Eirik)
+ [[Theonin][Theonin]] (Espen)
+ Ember Wolves (Thomas)
+ Shattered Lions (Mikke)

+ Oppdraget tar gruppen inn mot en landsby langs elven Tigeria,
  gjennom hovedsakelig skog og vegetasjon.
+ Gruppen nærmer seg landsbyen, og Shreya tar brått fingeren opp mot
  munnen og ser på Theonin. Det høres bjeff, men ikke hundeaktig --
  noe som virker menneskelig. Shreya mener at noen må lede dem unna,
  de har ikke tid til et slag her. Rekrutt Oxana Sanzavicha blir valgt
  ut.
+ Oxana skader seg og trekker frem blod, spytter opp i luften og
  prøver å lokke dem. Lyden av bjeff blir tydeligere, og det er klart
  at de nærmer seg raskt.
+ På en liten høyde oppdager Oxana at hun er omringet av mennesker,
  som alle står på på fire -- som dyr. De skriker, og Oxana faller
  ned, men tar tak i et tre på hengende håret.
+ Ember Wolves holder på å bryte rekkene, men Maleksei irettesetter
  dem med en tale. Oxana må ofres, uten at Ember Wolves får lov til å
  prøve å redde henne.
+ Gruppen ser så landsbyen, og Theonin bruker en kikkert til å se at
  noe er alvorlig galt med innbyggerne -- de er alle blitt
  gjennomboret av små, sylskarpe glassbiter.
+ Shreya feier vekk kommentarer om at det muligens er en felle, og
  hopper ned en høyde før hun beveger seg i retning landsbyen.
+ Maleksei har fått vite at gruppen _må_ redde Grevinnen, koste hva
  det koste vil. Blant de vandøde skal de se etter riddere, som holder
  Grevinnen. Shreya løper uforsvalig inn blant de vandøde.
+ Maleksei havner i skvis mellom en ridder i sort rustning, og
  vandøde, over elven midt i byen. Boran forsøker å få med seg resten
  av rekruttene i Ember Wolves, men blir fanget av en vandød med
  glasskniver boret inn i kroppen.
+ Boran, en rekrutt, forsøker å bevege resten av Ember Wolves til å
  komme Maleksei til unsetning. Talen faller ikke i smak, og mens
  Boran alene avanserer mot Maleksei blir han grepet fatt i av en
  vandød med glasskniver boret inn i kroppen. En av knivene stikker
  inn i leggen, og blod fosser ut. Boran, drevet til vanvidd av
  stress, mister fatningen og slår mot den vandøde, hjelpesløs. Han
  dør, omfavnet av den livsfarlige vandøde.
+ Oxana faller ned fra treet, men er på beina. Hun forsøker å forsvare
  seg fra de vandøde, men blir etterhvert overmannet, og dør. En
  sortkledd kvinne, bærende på en sort langbue, nærmer seg åstedet og
  ser ned på Oxanas rester. Hun setter foten ned på restene, og går
  videre.
+ Shreya sloss de udøde, og blir begravet i en masse udøde. Hun
  forsvinner inn i mengden, men sloss tydeligvis videre.
+ Maleksei møter den sorte ridderen, som forteller om Legionens
  håpløse situasjon. Det eneste, sier ridderen, er å sverge tro til de
  udøde. Maleksei angriper, og får dekningsild av Theonin. Han finter,
  og klarer å stikke sverdet inn i ansiktet til ridderen.
+ Resten av Ember Wolves tar til kamp og kjemper seg mot broen og
  Maleksei. Princep Anton Albrekt viser sin sanne karakter, og hogger
  ned de vandøde som står i veien. De kommer seg fram i sikkerhet.
+ Theonin får en død udød over seg, men kommer seg unna. Han går mot
  Shattered Lions, skyter i luften, og setter i gang med en tale for å
  oppmuntre til mot og handling. De løper mot broen, kommer også fram
  i sikkerhet.
+ Maleksei ser at de andre kommer, og presser mot to gjenværende
  riddere. Med dekningsild får Maleksei overmannet én av dem og kastet
  ham ned i elven, men stiller seg faretruende nær kanten av brua og i
  en dårlig posisjon. Broen er klarert, men Maleksei sitter i saksa.
+ Theonin fører an gruppene med rookies og kommanderer dem til å fyre
  av mot den gjenværende ridderen. Ridderen blir skutt, men uheldigvis
  skjer det samme med Maleksei -- han faller ned i elven.
+ Anton, Islanya og Scarlet speider etter Grevinnen, og Anton nærmest
  snubler inn en dør før han skriker høylydt -- han har åpenbart sett
  noe skrekkinngytende.
+ Maleksei kjemper i vannet, veid ned av rustningen han bærer. Gjennom
  strabaset kutter han seg opp og tar skade. Theonin haster ned i
  vannet og hjelper Maleksei, men hører brått skriket fra Anton.
+ Theonin og Anton går inn i bygningen, og de ser en gruppe mennesker
  som er hengt etter huden, nakne og blodige, fra taket. Én av dem er
  Grevinnen. Theonin forsøker å få et nærmere blikk på situasjonen,
  men blir overumplet av en ridder som angriper, fra siden innenfor
  inngangen.
+ Scarlet tar seg inn fra taket, og ser fra et galleri Grevinnen som
  henger fra lenker i taket. Gjennom en omfattende redningsaksjon
  klarer Scarlet å fire seg ned med et rep, får kontakt med Grevinnen
  og sammen klatre opp på galleriet. Vel oppe, dukker en ridder opp,
  og stikker med et sverd mot Scarlet. Grevinnen kvikner til, og
  dytter Scarlet vekk og ned fra galleriet igjen.
+ Theonin, i basketaket med ridderen oppdager at det kommer
  ytterligere enda en ridder. Han får bistand fra Islanya, og får
  anledning til å fyre av musketten på en slik måte at de
  uskadeliggjør begge ridderne.
+ Maleksei overvinner ridderen i vannet, og kommer seg til sikkerhet,
  tross store skader.
+ Scarlet klarer å skjære seg løs fra repet, og lander lett ned i
  første etasje av bygningen. Islanya og Anton løper frem og ser det
  som skjer med Scarlet. Islanya tar frem musketten og skyter mot
  ridderen som står oppe i galleriet. Scarlet, Islanya og Anton klarer
  å unnslippe ridderen og ta seg ut av bygningen.
+ Maleksei klarer å samle rookies til handling, og leder på nytt et
  tokt inn i taket og redder ut Grevinnen.
+ Sverenja Koveienicha av Shattered Lions blir hugget ned under
  flukten med Kontessa Hermina.
+ Shreya tar en pil i fart på vei mot Grevinnen, og den spidder
  hånden. Hun drar den ut, men konsekvensen er en sort vekst som
  vikler seg rundt armen, idet den slenger seg hit og dit utenfor
  Shreyas kontroll. Pilen ble skutt av den sortkledde jegeren.


** Kråkens Rede

+ [[Topaz][Topaz]]
+ [[Arun][Arun]]
+ Ghost Owls
