#+TITLE: Band of Blades – The Road to Skydagger Keep

* Karakterer

** Legionen

*** Shreya

 + En av de Utvalgte

*** Arun

 + Doktor/lege

*** Maleksei

 + Kranglet med [[Theonin][Theonin]], som ble irritert.

*** Theonin

 + Fikk en kikkert av [[Topaz][Topaz]].
 + Irriterer seg over [[Maleksei][Maleksei]].

*** Topaz

 + Ga en kikkert til [[Theonin][Theonin]], et minne fra hjemlandet.

*** Rashu Pakshi

 + Kommandør

*** Mana

 + Kvartermester

*** Marskalk

 + Marskalk

*** Anton

 + Krøkiker

** Blighter

*** Doktoren

+ Det ryktes at [[Doktoren][Doktoren]] var en vandød som fant tilbake sitt intellekt
  og selv, etter å ha blitt vendt om. Doktoren er kjent for sine
  grusomme eksperimenter.

* Lokasjoner

** Tigeria

+ Elv
+ Legionen unnslapp de vandøde ved å sabotere en bro som gikk over
  elven.

* Økter

** 5. februar

 + Legionen krysset et stykke unna Karlsburg en bro.
 + Spesialister snek seg ned til broen med hensikt å sprenge broen og
   sinke de vandøde.
 + [[Arun][Arun]] valgte å krysse vannet, under broen.
 + Oppdraget var en suksess, men det var på hengende håret: [[Maleksei][Maleksei]],
   [[Arun][Arun]] og [[Topaz][Topaz]] Dancing Sky havnet i vannet med en rekke vandøde
   følgende etter.
 + [[Theonin][Theonin]] holdt seg et stykke unna, og holdt utkikk over hele
   området. Med en kikkert han fikk av [[Topaz][Topaz]] Dancing Sky fikk han sett
   at ladningen var klar, og gitt signal om at kysten var klar. Han løp
   så ned til broen, og fyrte av en pil mot en sårbar del. Pilen traff
   på mirakuløst vis direkte og fikk satt broen ut av spill.

** 19. mars

+ Legionen har befestet seg på østsiden av elva [[Tigeria][Tigeria]].
+ Alle venter spent på [[Shreya][Shreya]], som forsvant litt før spesialistene dro
  ut på sabotasjeoppdraget.
+ Soldatene er spente, tause og engstelige.
+ [[Shreya][Shreya]] synes plutselig, bærende på en bylt. [[Shreya][Shreya]] skuer på
  nybegynnerne med et blikk som en jeger. Responsen er ærefrykt,
  henførthet uforstand, sinne.
+ Det viser seg at [[Shreya][Shreya]] bærer på en av [[Blighter][Blighter]] kreaturer. En kråke
  -- [[Doktoren][Doktoren]]. Hun etterlater seg [[Doktoren][Doktorens]] levninger, og forlater
  dem.
+ [[Arun][Arun]] oppdager en sort vekst som siver inn i armen. Han sover, og
  drømmer om en hvit kråke som faller om. Det slutter å pirke i
  såret. Det viser seg å være [[Shreya][Shreyas]] gjerning som leger ham for
  korrupsjonen i armen.
+ Det blir fest. Mana kaller [[Arun][Arun]] for en helt, for dåden han gjorde
  under sabotasjen av broen over [[Tigeria][Tigeria]]. Aruns brukkede arm blir
  leget, på bekostning av Fred.
+ Legionen avanserer mot Vestfronten, hvor det brenner og det er
  rester av våpen og katapulter. Vestfronten fungerer som et godt sted
  å hvile før ferden går videre til Plainsworth.

** 9. april

+ Arun blir spurt om å bli med på oppdraget [[Grevinnen][Grevinnen]], og melder
  seg med én gang. Han blir fortalt at planen er å dra om et par timer.
+ Shreya har reist seg opp og stirrer ut mot horisonten, etter at
  oppdragene har blitt valgt ut. Hun sier, «nå». Arun, som ikke har
  klart å bli med i tide, velger å bli med på oppdraget [[Kråkens Rede][Kråkens Rede]] isteden.

** 16. april

** 23. april

+ En kveld oppdager Adisha Darhdi en lukt av de vandøde, og varsler
  vaktholdet om den potensielle trusselen. Legionen klarer ikke å
  respondere, og de blir overrumplet. Det bryter ut kamp.
+ Rahika Kapatia dør.
+ Torm Coolhand dør.
+ Graf Anton Senacci dør.
+ Det blir gravferd for de døde, hvor levningene blir samlet og brent
  i verdige omgivelser, men med få ressurser til å lage flotte
  likbål. Sang og musikk følger med.

** 7. mai

+ I et mer eller mindre falleferdig telt holder generalstaben
  møte. Marskalken, nybarbert som alltid, har innført en daglig sjekk
  av våpen.
+ Det blir bestemt at Grevinnen og to speidere -- Adisha Darhdi og
  Topaz Dancing Sky -- sendes ut på oppdrag.

** 21. mai

+ Det brenner i Plainsworth. Brannen sprer seg raskt, og byen står
  straks i flammer. En flod av flyktninger forlater byen, og ankommer
  leiren i løpet av natten. Legionen hjelper dem.
+ De etterlatte forteller om menn i sorte rustninger som ledet
  mordbrannen. Hele bystyret er antatt drept.
+ Flyktningene er mange, og de er sultne. De krever mat og ressurser
  som legionen ikke kan spare, og de blir geleidet vekk.
+ En kvinnelig skikkelse, åpenbart forkledd og i skjul, ser ut som hun
  er med flyktningene men legger noe inn i teltet til Marskalk Jurij
  Sienkovich.
+ Marskalken blir overrumplet av en sort masse tentakler som veller ut
  av skrinet som ble lagt i teltet. Han klarer å ringe en alarmbjelle
  og rope etter fakler.
+ Tentakler vokser ut av hånda på Marskalken, samtidig som tentaklene
  i skrinet krymper. Marskalken tar hånda inn i en flamme, og
  tentaklene blir til aske.
+ I skrinet befinner det seg en finger, med navnet "Shreya" risset inn
  i kjøttet.
+ Krønikeren skriver febrilsk på noen ark, og studerer
  fingeren. Etterhvert beveger den på seg.
+ Fred dukker opp, som straks faller om ved synet av fingeren. Han
  mumler "Shreya... Shreya...", og er ikke ved full bevissthet.
+ Voyis snakker med Marskalken. Han hevder at Askekongen er nær. Han
  holder fram høyrehånden, og viser arrene. Han sier, "det er ingen
  ære i det som venter oss", og snur ryggen for å gå.
+ Voyis advarer om at Shreya kan måtte komme tilbake som "noe annet".
+ Marskalken siterer fra et epos, "stål lyner om dagen".
+ Dania fra Silver Stags er full, grytidlig en morgen. Aleksa fra
  Shattered Lions anklager henne for å ha stjålet hennes vin. Dania
  rygger, og snubler over Maleksei. Hun blir tatt hånd om av Maleksei,
  som sender henne på en løpetur for å bli gjort edru.
+ Legionen går videre, og ankommer omsider Sunstrider Camp. Denne er
  fylt av flyktninger, som har fått tilgang i vintertiden. Hestefruen
  Tsaga eier noen av de permanente bebyggelsene, og den spesielle
  hesterasen Ildmaner avlet fram av Tsaga er viden kjent. Området
  rundt er preget av banditter.
+ 


** 28. mai

+ Intel-spørsmål:
  + What would be a useful item to bring on this mission?
    + Reliquiaries
  + What's a challenge we might face on this mission?
    + Ambush
  + Which way are the broken moving?
    + Render: Nordover langs elven
    + Blighter: Østover over fjellene


** 4. juni

+ Star Vipers nekter å dra ut på et mindre rekognoseringsoppdrag. De
  mener at deres kaptein Valeria urettmessig ble tatt vekk fra dem,
  sammen med fanebæreren Nadit.
+ Vermillion Spreading Blaze drikker vin, og legger ut om
  mellomoffiserene som rapporterer til sentralkommandoen. "De er aldri
  ute i felten, og koser seg med ledelsen".
+ De blir skjelt ut av mellomoffiseren og Marskalken, og tar til
  fornuft. De skåler en siste gang for Valeria og Nadit, og fornyer
  sine løfter til Star Vipers kjernefilosofi, "vi skinner i natten".
+ Marqui Cyprian Rodano

* Oppdrag

** Grevinnen

+ [[Shreya][Shreya]]
+ [[Maleksei][Maleksei]] (Eirik)
+ [[Theonin][Theonin]] (Espen)
+ Ember Wolves (Thomas)
+ Shattered Lions (Mikke)

+ Oppdraget tar gruppen inn mot en landsby langs elven Tigeria,
  gjennom hovedsakelig skog og vegetasjon.
+ Gruppen nærmer seg landsbyen, og Shreya tar brått fingeren opp mot
  munnen og ser på Theonin. Det høres bjeff, men ikke hundeaktig --
  noe som virker menneskelig. Shreya mener at noen må lede dem unna,
  de har ikke tid til et slag her. Rekrutt Oxana Sanzavicha blir valgt
  ut.
+ Oxana skader seg og trekker frem blod, spytter opp i luften og
  prøver å lokke dem. Lyden av bjeff blir tydeligere, og det er klart
  at de nærmer seg raskt.
+ På en liten høyde oppdager Oxana at hun er omringet av mennesker,
  som alle står på på fire -- som dyr. De skriker, og Oxana faller
  ned, men tar tak i et tre på hengende håret.
+ Ember Wolves holder på å bryte rekkene, men Maleksei irettesetter
  dem med en tale. Oxana må ofres, uten at Ember Wolves får lov til å
  prøve å redde henne.
+ Gruppen ser så landsbyen, og Theonin bruker en kikkert til å se at
  noe er alvorlig galt med innbyggerne -- de er alle blitt
  gjennomboret av små, sylskarpe glassbiter.
+ Shreya feier vekk kommentarer om at det muligens er en felle, og
  hopper ned en høyde før hun beveger seg i retning landsbyen.
+ Maleksei har fått vite at gruppen _må_ redde Grevinnen, koste hva
  det koste vil. Blant de vandøde skal de se etter riddere, som holder
  Grevinnen. Shreya løper uforsvalig inn blant de vandøde.
+ Maleksei havner i skvis mellom en ridder i sort rustning, og
  vandøde, over elven midt i byen. Boran forsøker å få med seg resten
  av rekruttene i Ember Wolves, men blir fanget av en vandød med
  glasskniver boret inn i kroppen.
+ Boran, en rekrutt, forsøker å bevege resten av Ember Wolves til å
  komme Maleksei til unsetning. Talen faller ikke i smak, og mens
  Boran alene avanserer mot Maleksei blir han grepet fatt i av en
  vandød med glasskniver boret inn i kroppen. En av knivene stikker
  inn i leggen, og blod fosser ut. Boran, drevet til vanvidd av
  stress, mister fatningen og slår mot den vandøde, hjelpesløs. Han
  dør, omfavnet av den livsfarlige vandøde.
+ Oxana faller ned fra treet, men er på beina. Hun forsøker å forsvare
  seg fra de vandøde, men blir etterhvert overmannet, og dør. En
  sortkledd kvinne, bærende på en sort langbue, nærmer seg åstedet og
  ser ned på Oxanas rester. Hun setter foten ned på restene, og går
  videre.
+ Shreya sloss de udøde, og blir begravet i en masse udøde. Hun
  forsvinner inn i mengden, men sloss tydeligvis videre.
+ Maleksei møter den sorte ridderen, som forteller om Legionens
  håpløse situasjon. Det eneste, sier ridderen, er å sverge tro til de
  udøde. Maleksei angriper, og får dekningsild av Theonin. Han finter,
  og klarer å stikke sverdet inn i ansiktet til ridderen.
+ Resten av Ember Wolves tar til kamp og kjemper seg mot broen og
  Maleksei. Princep Anton Albrekt viser sin sanne karakter, og hogger
  ned de vandøde som står i veien. De kommer seg fram i sikkerhet.
+ Theonin får en død udød over seg, men kommer seg unna. Han går mot
  Shattered Lions, skyter i luften, og setter i gang med en tale for å
  oppmuntre til mot og handling. De løper mot broen, kommer også fram
  i sikkerhet.
+ Maleksei ser at de andre kommer, og presser mot to gjenværende
  riddere. Med dekningsild får Maleksei overmannet én av dem og kastet
  ham ned i elven, men stiller seg faretruende nær kanten av brua og i
  en dårlig posisjon. Broen er klarert, men Maleksei sitter i saksa.
+ Theonin fører an gruppene med rookies og kommanderer dem til å fyre
  av mot den gjenværende ridderen. Ridderen blir skutt, men uheldigvis
  skjer det samme med Maleksei -- han faller ned i elven.
+ Anton, Islanya og Scarlet speider etter Grevinnen, og Anton nærmest
  snubler inn en dør før han skriker høylydt -- han har åpenbart sett
  noe skrekkinngytende.
+ Maleksei kjemper i vannet, veid ned av rustningen han bærer. Gjennom
  strabaset kutter han seg opp og tar skade. Theonin haster ned i
  vannet og hjelper Maleksei, men hører brått skriket fra Anton.
+ Theonin og Anton går inn i bygningen, og de ser en gruppe mennesker
  som er hengt etter huden, nakne og blodige, fra taket. Én av dem er
  Grevinnen. Theonin forsøker å få et nærmere blikk på situasjonen,
  men blir overumplet av en ridder som angriper, fra siden innenfor
  inngangen.
+ Scarlet tar seg inn fra taket, og ser fra et galleri Grevinnen som
  henger fra lenker i taket. Gjennom en omfattende redningsaksjon
  klarer Scarlet å fire seg ned med et rep, får kontakt med Grevinnen
  og sammen klatre opp på galleriet. Vel oppe, dukker en ridder opp,
  og stikker med et sverd mot Scarlet. Grevinnen kvikner til, og
  dytter Scarlet vekk og ned fra galleriet igjen.
+ Theonin, i basketaket med ridderen oppdager at det kommer
  ytterligere enda en ridder. Han får bistand fra Islanya, og får
  anledning til å fyre av musketten på en slik måte at de
  uskadeliggjør begge ridderne.
+ Maleksei overvinner ridderen i vannet, og kommer seg til sikkerhet,
  tross store skader.
+ Scarlet klarer å skjære seg løs fra repet, og lander lett ned i
  første etasje av bygningen. Islanya og Anton løper frem og ser det
  som skjer med Scarlet. Islanya tar frem musketten og skyter mot
  ridderen som står oppe i galleriet. Scarlet, Islanya og Anton klarer
  å unnslippe ridderen og ta seg ut av bygningen.
+ Maleksei klarer å samle rookies til handling, og leder på nytt et
  tokt inn i taket og redder ut Grevinnen.
+ Sverenja Koveienicha av Shattered Lions blir hugget ned under
  flukten med Kontessa Hermina.
+ Shreya tar en pil i fart på vei mot Grevinnen, og den spidder
  hånden. Hun drar den ut, men konsekvensen er en sort vekst som
  vikler seg rundt armen, idet den slenger seg hit og dit utenfor
  Shreyas kontroll. Pilen ble skutt av den sortkledde jegeren.


** Kråkens Rede

+ [[Topaz][Topaz]]
+ [[Arun][Arun]]
+ Ghost Owls

+ Gruppen rir raskt mot målet, og setter fra seg hestene et stykke
  unna. De avanserer, men blir raskt overrumplet, hvorpå en soldat i
  Ghost Owls -- Gallant Rubin Garossi -- blir begravet under en bølge
  av vandøde.
+ Kråkens Rede er råttent, og omhyllet av en grågrønn tåke som beveger
  seg unaturlig mot vinden. Det skjer grusomme, industrielle prosesser
  mot offere: det kan se ut som de blir tvangsforet med et stoff som
  virker å være etsende.
+ Et stykke unna sentrum for disse prosessene kravler en person seg
  framover. Hun lider, og Arun kneler ved siden. Noe er alvorlig galt:
  magen buler ut, og kvinnen kaster opp en etsende masse som treffer
  Arun i siden. Smertene fortsetter, og Arun blir tvunget til å gjøre
  ende på kvinnen for å spare henne for videre elendighet.
+ Noen av veggene ser ut til å ha blitt etset vekk, og avslører for
  soldaten Aswina Kathri våpen og ei bok. Boka dokumenterer
  grusomme eksperimenter og forsøk, skrevet følelsesløst og
  systematisk. I margen står det ført ned notater, som åpenbart bærer
  sterke følelser. Notatene omhandler /Blighter/ -- Skjenderen -- og
  to andre som forfatteren ser ut til å ha brydd seg inderlig om. En
  datter og en ektemann. Ordet hevn er streket under mange ganger. Det
  som følger ordet «gjennombrudd» er: Skjenderen = Elenessa. Svakhet =
  Shreya.
+ Ivanka Ijaviecha bryter ut om Gallant Rubin at alt gir mening. Hun
  beskriver på en bisarr måte hvordan Rubin må være i live og valgte å
  sette seg i livsfare for Shreya. I hennes ord måtte Shreya ha et
  forsyn og en styrende hånd med på dette oppdraget, og gjort at
  resten overlevde. På ferden tilbake blir hun mer og mer distrahert,
  og bryter ut om umulige syner av Shreya. Når de slår leir foreslår
  Ivanka å ta første vakt. Underveis i vakta er det tydelig at Ivanka
  ser noe ute i skogen, og går vekk fra leiren. Hun kommer aldri
  tilbake.
+ På vei tilbake opplever de resterende, med tankene på Shreya, at
  armene nærmest er paralysert av kulde. Ikke før de når Legionen er
  kuldefornemmelsene over.


** Oppdraget for å hente inn Isfuglen (Kodenavn Isfugl)

+ Grevinnen
+ Arun Manabur
+ Topaz Dancing Sky
+ Ghost Owles

+ Arun Manabur får et sideoppdrag om å beskytte Grevinnen, men
  samtidig passe på at hun ikke har blitt et offer for korrupsjon
  under fangenskapet.
+ Gruppen marsjerer langs fjellinjen, og kommer etter 3 dager fram til
  en landsby i skogen. Tempelet ligger ved tvillingfossen, og fra den
  renner en elv gjennom landsbyen. Der ser gruppen noen landsbyboere
  forsøke å drukne noen i elven.
+ Tvillingfossen er en naturlig relikvie – noe som er igjen fra de
  utvalgte. De kjetterske innbyggerne har valgt å tilbe fossen som et
  naturlig fenomen, i strid med den rette tro og lære. «Drukningen» er
  en form for eksorsisme.
+ Rekrutten Elena råder Grevinnen til å gripe inn i situasjonen, og
  Grevinnen ser seg enig.
+ Eksorsismen fører til at personen dør, og blir holdt livløs oppe fra
  elven. Arun kaller det for hedensk aktivitet, og oppfordrer til å
  holde seg unna. Grevinnen mener at kjetteriet nettopp er en grunn
  til å nærme seg, for de må ledes til den rette tro.
+ Situasjonen eskalerer, og Grevinnen skyter med en signalpistol for å
  ta oppmerksomheten til landsbyboerne.
+ Landsbyboerne taler til Grevinnen, og sier at demonen kom til
  landsbyen for noen uker siden. Den fortalte mange vakre ord, og
  lovpriset den vakre fossen. Demonen søkte asyl i tempelet, men med
  oppholdet kom en forbannelse over landsbyen. En dag så de et lik ved
  fossen, og et lysglimt på toppen av høyden, som fra en rustning.
+ Arun og Elena forsøker å ta seg til elven, men landsbyen tillater
  bare Elena å nærme seg. Underveis mot liket oppdager Topaz Dancing
  Sky en vakt som sikter mot Elena med en børse.
+ Vakten har noe unaturlig som buler ut under armen. Han skyter, og
  lyden virker å være forsterket. Skuddet suser forbi Elena, som
  benytter anledningen til å løfte opp kroppen til den druknede
  kvinnen og løper mot Arun.
+ Arun og Elena gir livreddende hjelp, og klarer å redde henne fra
  drukningsdøden. En stor masse vann fra lungene kommer ut og treffer
  Arun, og kvinnen hoster så kraftig at tungen hennes er synlig. På
  tungen var det et øye. Kvinnen løper så vekk.
+ Etter å ha snakket med innbyggerne, lærer gruppen at vannet må ha
  blitt forgiftet, eller er besudlet på noen måte. Topaz Dancing Sky
  foreslår til en av innbyggerne at de bør bli med Legionen mot
  Skydagger Keep.
+ Gruppen begir seg opp en skjult sti, høyere opp fjellet. Der ser de
  Tempelet som er godt bygget; et gudommelig syn 
+ Topaz går først inn i tempelet og finner Isfuglen sittende på en 
  sirkulær platform foran fossen. Foran alteret finner de elvesteiner
  (slipte blokker) foran alteret man må hoppe over på. I tempelet er
  det ikke lett å se om gulvet, som er dekket av vann er et speilbilde
  eller fortsetter i evigheten nedover. Man kan se en sort skygge av
  et dyr som svømmer i vannet. Når man ser på den så forsvinner den.
+ Topaz blir truet av isfuglen idet hun kommer inn. "Hvis du fortsetter
  kan jeg ikke garantere at du er trygg". Sirkulær platform innerst ved
  fossen. Isfuglen sitter der. "Jeg vil ikke skade dere. Jeg råder
  dere til å trekke dere tilbake".
+ Contessa og Arun prøver å snakke Isfuglen ned fra å gjøre noe dumt og
  få han til å komme med dem tilbake til leiren. Topaz forsøker å komme
  seg over til isfuglen, men steinene han står på begynner å begeve seg.
+ Arun kaster seg ned i vannet for å forsøke å få oppmerksomheten til dyret
  i vannet. Får oppmerksomheten til noen mindre dyr og delvis til den store.
  Topaz kommer seg over og forsøker å få Isfuglen til å bli med tilbake til
  leiren. Isfuglen beveger handen til sliren sin nærmest automatisk, som
  en refleksiv handling.
+ Topaz holder frem et relikvie av (et gammelt kompass av en av oldtids profet)
  og viser det frem. Isfuglen ikke overbevist av relikviet og griper tak i Topaz.
  Det synes to arr på armen til Isfuglen som åpner seg som munner og begynner
  å bite etter Topaz. Arun skyter varselsskudd over hodet til Isfuglen og 
  formaner ham til å snakke med Contessaen. Cue flashback.
+ I en flashback så viser det seg at Contessa og Isfuglen har en bakgrunn som går
  åresvis tilbake. Det blir kjent at isfuglen egentlig heter VOYIS KARIYEVICH.
  Contessaen har rekvirert tjenestene til legionen og contessaen
  har brukt sine betydlige midler til å betale dem. De møtes på en bro utenfor
  Karlsburg etter Isfuglen og legionen har hamlet opp med en gruppe banditter
  De drikker vin sammen. Contessaen har vært fascinert av Isfuglen, hvordan han
  oppfører seg annerledes fra resten av offiserene og hvordan han har vært i ilden
  tidligere.
  Isfuglen lurer på hva de gjør, om de går rundt og leker imperiet. Maten de
  spiser kan jo mate mange familier. Contessaen overtaler Isfuglen til at han
  allerede har hjulpet mange familier ved å stoppe disse banditten.
  Contessaen får Isfuglen til å love at dagen han henger opp sverdet skal han komme
  og finne henne og jobbe for legionen.
  Ser noe som gløder faretruende rødt på horisonten. Askekongen har kommet.
+ Tilbake i tempelet så roper Contessa ut fornavnet til Isfuglen for å få han
  ut av transen og bryte gjennom korrupsjonen til menneskligheten hans. Navnet
  runger gjennom tempelet og stirrer på Contessa. Voyis husker plutselig
  contessaen og "Husker du hva du lovet meg? Du lovet du skulle bli med oss".
+ Voyis erindrer at en av landsbyboerene hadde blitt bitt og søkt til tempelet
  for å dø. Isfuglen drakk blodet hennes. Askekongens korrupsjon går dypt i
  sjelen til Voyis. Contessa overtaler allikevel Voyis til å ofre seg. Voyis
  kaster seg ned i vannet for å hente Topaz som har falt uti.
+ Arun ber Elena av Ghost Owls kutte bort dyrene som sitter i huden hennes. 
  Kuttet går ganske dypt og Arun får et kutt i pulsåren.
+ Topaz befinner seg under vann og kjemper mot en fisk. Klarer å drepe den og
  blir dratt til overflaten av Voyis. Arun kaster seg over Voyis og dekker 
  korrupsjonen på kroppen til Voyis med noen filler fra en av de falne
  utvalgte fra slaget ved Aldermark og heller tonic over såret. Korrupsjonen
  løftes fra Voyis og han blir bært tilbake til leiren.
+ På ferden tilbake møter de en familie fra landsbyen som blir med dem.


** Garossi Herregård (Operasjon Huspass)

+ Adisha Darhdi
+ Maleksei
+ Shattered Lions
+ Riddere av den sorte eik har tatt over Garossi Herregård. Gruppen
  velger et vågalt frontalangrep for å gjenerobre eiendommen.
+ Graf Leon Utrecht og Arun Dewa dør i operasjonen.
+ Spesialistene og resten av rekruttene sveiper gjennom rommene,
  unngår, overlister og overvinner ridderne.
+ Maleksei blir overmannet og stukket i ryggen, men Adisha gjør en
  fantastisk akrobatisk manøver for å angripe og nøytralisere
  angriperen. Det blir brytingskamp, men angriperen blir til slutt
  gjort ende på.

* Scarlets Drøm

+ Ember Wolves
  + Islanya
  + Scarlet Charging Spear
+ Contessa Hermina
+ Theonin
+ Det er høst, og gruppen skuer mot en vakker, fargerik fjellside.
+ Et landemerke får straks Scarlet til å se at de er på rett
  plass. Det er en slette, relativt flat. Midt gjennom sletten er det
  en sti, hvor det står en steinformasjon. Steinene står rett opp, med
  et overbygg, og danner en slags port gjennom hvilket stien går. Det
  sies at de som går gjennom vil unngå lyn på resten av reisen.
+ Scarlet Charging Spear har et forhold til denne steinformasjonen, da
  hun var vitne til at hennes mentor ble permanent skadet i et
  bandittangrep her, da hun var liten.
+ Vel framme plasserer Theonin seg et stykke vekk fra steinformasjonen
  og speider etter fare. Scarlet, Contessaen og resten av Ember Wolves
  går inn.
+ Scarlet opplever sterke inntrykk, eller minner fra drømmen hennes,
  og hun strekker seg fram for å røre ved en haug hun husker at
  hjorten begravde noe i.
+ Contessaen oppdager at de reisende har unaturlige uttrykk, og de
  spyr med ett ut en etsende masse som nesten treffer henne. Men hun
  klarer å unngå det, samtidig som hun trekker unna Scarlet.
+ Scarlet klarer samtidig å ta noe ut fra haugen på bakken. Det er
  kniven hennes, som hun gav til Shreya. Når hun rører ved kniven
  faller hun om, og blir bevisstløs.
+ Theonin ser at noen spitters og en kråke står på overbygget over
  resten av gruppen. En signalbluss fyres av fra gruppen som befinner
  seg under steinformasjonen, og Theonin skyter kråken.
+ Contessa beveger seg vekk fra sentrum av konflikten, men får med ett
  problemer da Scarlet ikke er ved bevissthet. Hun forsøker å løfte
  henne opp for å bære henne vekk. Redningsforsøket lykkes delvis; De
  kommer seg i sikkerhet men Contessa tar alvorlige syreskader.
+ Theonin får øye på Lugos, en høytstående løytnant som virker å være
  en maskin, og sikter umiddelbart med rifla. Lugos bærer et nag mot
  Theonin etter å ha møtt ham tidligere. Lugos blir uskadeliggjort, da
  sveiven på hans maskineri blir truffet.
+ De vandøde beveger seg ut av steinformasjonen, og posisjonerer seg
  rundt Theonin, tilsynelatende for å avskåre han. Theonin reagerer på
  dette og flykter.
+ Scarlet er tilbake der hun opprinnelig møtte Shreya, i en slags
  visjon. Shreya er skadet, men smiler. Hun nevner Blighters tropper,
  en hærskare av de råtne, ledet av Lugos. Hun sier at hun har søkt
  tilflukt i Asrikas tempel, som er i nærheten. Tempelet ligger ved en
  dal, og for å komme opp til tempelet er det lettest å gå gjennom
  dalen. Hun sier at hun legger en felle i dalen, og det er viktig at
  de vandøde ikke kommer seg ut av dalen før det er for sent. Shreya
  sier, "takk igjen, Scarlet".
+ Scarlet våkner til bevissthet, og tar seg opp på beina. Contessa
  roper til resten av soldatene i Ember Wolves at de skal gjøre
  retrett. Baroness "Firespear" blir truffet av en syrekladd og
  dør. Alika løper helt i feil retning. Anton og Islanya kommer seg unna.

* Hesteherren Nettars Hester

+ Adisha
+ Star Vipers
+ Oppdraget lykkes, og tre hester blir bragt til legionen, men Adisha
  tar skade.
+ Det er på hengende håret at gruppen klarer seg. Først klarer Valeria
  nesten å avsløre seg ved å høylytt skryte av et tidligere oppdrag,
  når det var meningen at de skulle holde en stille profil. De blir
  oppdaget når en av vaktene kaster en sneip ut i gresset, som treffer
  Valeria.
+ Star Vipers rir hestene vekk, men Valeria og Nadit blir igjen for å
  stoppe fienden fra å forfølge dem. De blir hugget ned i kampen.
+ Victoria Carlhove, en av Blighters løytnanter, befinner seg blant
  fienden.
+ Star Vipers må ta en omvei for å unngå en fiendtlig stasjon, men
  tross forsinkelser så kommer de vel fram.
+ Adisha blir skutt i basketaket.
+ Valeria og Nadit våkner opp igjen en stund etter oppdraget, men
  finner at de ikke lenger har sine menneskelige bein. De er
  tilsynelatende blitt erstattet av hestebein! Victoria Carlhove synes
  å skrive ned i en notablokk, mekanisk og uten følelser.
  
* Shreyas felle
+ Ryktet sprer seg i leiren om at Shreya er fredfull til sinns og klar
  for å dø. Dette er sant, men Shreya har ikke gitt opp helt enda og
  har fortsatt tro på at Topaz kan gjøre et mirakel.
+ Ankommer tempelet som ligger på en kolle. Store statuer på hvert
  hjørne av tempelet. Eneste trygg vei inn gjennom dalen vest for
  tempelet. De vandøde er der allerede og har begynt å avansere gjennom
  dalen. En grotesk skapning klatrer opp på en stein og begynner å
  kommandere de vandøde.
+ Legionen ligger i bakhold og venter på at Shreyas felle settes i
  spill. Voyis kjemper mot korrupsjonen i seg selv. Topaz gjør seg
  klar til å klatre opp fjellveggen for å komme seg opp til Shreya.
+ Shreya står plutselig ved en av steinene og et enormt lys danner
  seg over tempelet. Statuen lyser opp og varmen treffer huden til
  alle som står i nærheten. Statuen begynner å gli ned mot munningen av
  dalen og knuser de vandøde som står der. Dette sperrer dalen, men det
  er et lite mellomrom i steinen. Beistet tvinger alle innover og kaster
  de som ikke kommer seg frem over steinen. Et nytt krakk og en ny 
  stein faller ned som sperrer de vandøde inne. Et regn av brennende
  busker faller ned i dalen og tenner det tørre gresset og de vandøde
  begynner å dø.
+ Voyis maner opp soldatene til kamp og stormer fremover for å holde dem
  i dalen. De kommer raskt frem og scarlet og hennes lag hever riflene
  og skyter en salve med svartskudd inn i monsteret ved navn Wailer. Skuddene
  treffer, men eksplosjonene treffer og preller av. Wailer stormer mot Ember
  Wolves og kaster dem til siden. Princep Anton blir spidded på en metalltagg,
  Scarlet blir også spiddet på kroppen til Wailer, men er i live. Voyis kaster
  seg bakover og sverdet sitter fast i Wailer. Wailer går tilbake til å
  forsøke å heve sperringen, men isfuglen stormer på bakfra og stikker hen med
  en kniv.
+ Samtidig forsøker Topaz å snike seg usett rundt flanken for å komme
  frem til fjellveggen. Det viser seg å være vanskelig, men hun forsøker
  allikevel. Men kråkene har dannet en speiderposisjon på flanken og hun
  klarer ikke å komme seg frem til veggen usett. Hun må ta en lang vei rundt.
  Begynner å klatre opp veggen og faller ned, skader seg. Tiden går og det har
  allerede kommet noen råtnende opp til platået.
+ Scarlet Charging Spear blir ved et uhell hogget til av Voyis, idet
  han angriper Wailer. Ironisk nok blir hen presset inn i en av
  Wailers kroppsspyd.
+ Voyis plasserer en bombe inne i Wailer, men blir holdt fast idet han
  forsøker å komme seg unna. Blir tatt i eksplosjonen og påvirket av
  korrupsjonen.
+ Islanya, siste av Ember Wolves, maner opp moralen og oppfordrer alle
  til å gjøre et siste angrep mot Wailer. Melislav, en rookie i
  Grinning Ravens, er frosset i frykt. Albe, en annen rookie i samme
  tropp, prøver å riste av denne paralysen.
+ Grinning Ravens gjør klar og fyrer av en salve med blackshot, og
  klarer nesten å gjøre ende på Wailer.
+ Topaz Dancing Sky fortsetter ferden opp høyden, men ender opp med å
  bli oppdaget av kråkene. Vel oppe på platået ser hun et frodig
  landskap, med oliventrær som dominerer landskapet. På midten, oppe
  på en pidestall, ligger Shreya. Hun ser opp på Topaz, men er bare
  halvveis ved bevissthet.
+ Islanya gjør klar en eksplosjonsinnretning satt sammen av lampeolje,
  og kaster dette mot Wailer. Uheldigvis sprer flammene seg lenger ut
  fra kampområdene. Hun holder på å bli alvorlig skadet, men klarer å
  rulle seg unna, og pådrar seg bare noen skrubbsår. Vandøde tar fyr.
+ Wailer svaier fra side til side, brøler, og avanserer mot Grinning
  Ravens, og er Voyis er i fare for å bli trampet ihjel.
+ Albe maner opp til et siste angrep mot Wailer. Med krigsrop som
  lyder, «for Voyis!», så fyrer troppen av en salve. Wailer blir
  beseiret, og det bryter ut jubel blant soldatene.
+ Topaz Dancing Sky bærer Shreya ut av lunden og ned mot høyden, og
  forbereder å fire ned Shreya med tau.
+ Melislav og to andre klarer å bære Voyis vekk fra ilden som sprer
  seg med voldsom kraft, og kommer seg i sikkerhet. Grevinne Albe og
  en annen beveger seg også inn i sikkerhet.
+ Islanya blir igjen og holder vakt over Voyis, mens Melislav, Albe og
  resten av Grinning Ravens løper inn i det røykbelagte landskapet i
  leting etter Topaz og Shreya. Albe går tapt inne i røyken, etter å
  ha trukket sverd og avansert inn. Melislav kommer til skade i å
  skyte Reina, og løper etterhvert tilbake i frykt for sitt våpen,
  røyken og hele situasjonen.
+ Topaz Dancing Sky klarer å senke seg og Shreya ned fra høyden, og
  klarer på hengende håret å motstå seg at en mystisk kraft siger ut
  av Shreya og inntar henne. Kraften virker å være bundet til det at
  Shreya er /Utvalgt/, og blir holdt tilbake.
+ En betydelig såret gruppe står igjen etter slaget, og tar seg sakte
  tilbake til Legionen: Topaz Dancing Sky, Islanya, Melislav, Shreya
  og Voyis.

+ Topaz Dancing Sky
+ Voyis "Isfuglen" Kariyevich
+ Ember Wolves
+ Grinning Ravens

* Urverksmonsteret
+ Theonin og Shattered lions setter ut på jakt etter Lugos. De finner spor
  ved steinene hvor de tidligere ble tatt i bakhold. De finner en ruin
  hvor Lugos gjemmer seg. Lugos ligger som en avskrudd maskin på en vogn
  rundt noen kråker. Det er noen mennesker der som blør. 
+ De forsøker å distrahere vaktene med brann og Sevrenja stiller seg på
  andre siden for å gjøre klart skuddhold, men blir oppdaget. Ekrik 
  befinner seg på en annen side og distraherer menneskene ved å trille
  tønner nedover bakken. Aleksa har tent et bål med ild, men tønnene triller
  rett imot henne og kråkene har oppdaget henne. Kråkene kommer rett imot
  henne, men tønnene kommer trillende imot dem imens de lekker en svart
  substans. Aleksa kaster fakkelen og de sorte stripene på bakken etter
  tønnene tennes.
+ Theonin ser på Lugos i kikkerten sin og ser den maktesløse kroppen hans
  liggende der. Men så blir han usikker på om dette virkelig er "den mektige
  lugos" og blir redd for at det er et bakhold og roper retrett. Ingen av
  rekruttene får med seg dette og han bestemmer seg for å gå inn og redde 
  Aleksa ut av infernoet som hun nå befinner seg i. Han kaster seg inn i
  flammene og finner Aleksa inne i flammene. Hun blir reddet ut og blir så
  betatt av Theonin som redder henne ut.
+ En gammel dame kommer gående mot Lugos og kutter seg over han slik at 
  det svarte hjertet i maskineriet hans begynner å slå. Han reiser seg og
  dreper en av menneskene som står rundt han. Så løper han etter Aleksa, og
  Theonin innser at den eneste muligheten han har for å overleve er å ofre
  Aleksa. Så han sparker henne inn i Lugos og redder seg selv. Men Ekrik ser
  dette og blir sjokkert. Theonin løper gjennom skogen for å forsøke å
  flykte mens han mumler "det var henne eller meg, jeg har en familie å
  komme meg hjem til"! Ekrik ser dette og tenker han er en forræder som
  stikker fra sine soldater. Han maner seg selv til mot og forsøker å felle
  Lugos ved å dynke seg selv i olje og kaste seg over Lugos ved å tenne på
  seg selv. "For legionen og menneskeheten" hørt Sveranja idet skogen og 
  Lugos går opp i flammer. Så ser man Lugos komme ut av infernoet som en
  Terminator. Lugos vender seg rundt og jager etter Theonin. Theonin kaster
  en pose med krutt på bakken idet han flykter og kaster seg rundt et tre
  for å ta opp skuddhold og idet Lugos kommer løpende skyter på kruttet og
  springer fellen sin. Kruttet sprenger og Lugos tar fyr og mister balansen.
  Men han kommer seg raskt videre og idet Theonin snubler på en stein kommer
  Lugos og plukker han opp og stirrer dypt inn i øynene hans idet han
  tvinger et skarpt sverdblad mot hodet til Theonin. I øyeblikket før han
  ender Theonin stopper Lugos - fjærene som drev urverket til Lugos har
  gått tom for kraft og han stopper. Theonin overlever og Sveranja hjelper
  han ned. Lugos blir uskadeliggjort og de drar tilbake til leiren.
+ Tilbake i leiren er stemningen dårlig etter å ha mistet totalt ni folk på
  oppdrag. Voyis kommer til skade for å vise frem korrupsjonen sin for
  Shreya og hun går bestemt for å avslutte livet hans. Shreya river av
  armene hans mens Theonin forsøker å stoppe henne ("hun har gått berserk!").
  Korrupsjonen i Voyis kommer til overflaten og han angriper Maleksei. Et
  basketak forespiller seg og ender med at Islanya skyter Voyis død.
  Contessaen kommer inn og ser Voyis ligge død foran Maleksei. Hun kneler ned
  foran han og feller en tåre idet han sier sine siste ord til sin kjære.
  "Jeg prøvde å holde korrupsjonen tilbake men han var for sterk. Jeg..
  Prøvde". Theonin er overbevist om at Voyis kunne vært reddet og at det var
  på grunn av Shreyas provokasjon at Voyis tapte kampen til korrupsjonen.
+ Lorekeepers historie: Legionen masjerte mot slottet Schloss Doderblitz og
  beleiret det. Chosen Dalmatia velsignet av guden for kunnskap og hukommelse.
  Tusenvis av zemyati kom til unnsetning og brøt ned slottets forsvar. Når
  slottet ble tatt fant de bein som var gnagt på. De hengte Storm som hadde
  skapt et stort uvær i området. Siden den dag har zemyati alltid trukket mot
  legionen og vært modige og lojale til legionen.

* Den Grå Handelsmannen

+ Kontessa Hermina
+ Maleksei Dragovich
+ Silver Stags
+ Den Grå Handelsmann ble nevnt flere ganger i krøkikene. For 15 år
  siden var det et bondeopprør mot prisene den Grå Handelsmannen gav
  for korn og poteter, og Legionen ble hyrt inn for å bekjempe
  denne. Legionen endte opp med å stå i gjeld til den Grå
  Handelsmannen.
+ I krøniken er det skrevet i margen, om Den Grå Handelsmann: «Vokt
  dem for enhver avtale».
+ Kontessa Hermina, Maleksei og Silver Stags ror en liten båt i
  retning handelsmannens øy, en tur som tar omtrent 5 timer. Båten er
  egentlig ikke stor nok til å romme alle om bord, men det var det
  eneste som var tilgjengelig.
+ De nærmer seg, og været skifter plutselig til å bli en storm. Foran
  dem er det en båt som har forlatt øya, og som blir truffet av et lyn
  fra himmelen. Båten er i fyr.
+ Kontessa Hermina gir ordren om å ro nærmere båten, og se om det er
  noen som kan reddes.
+ En skikkelse synes på båten, hengende over siden. Elrika strekker
  seg ut av båten for å se nærmere, med hjelp av Maleksei. Hun kan
  melde om at skikkelsen er tydelig i handelsmannens tjeneste – hun
  gjenkaller en historie fortalt av Krønikeren om en mulig forbannelse
  som hersker over de som går i tjeneste.
+ Elrika og Dania får dratt skikkelsen over og om bord i båten, og vi
  ser at den skapningen har rett og slett utseendet til en frosk –
  huden er slimete, fingre og tær er blitt vevet sammen til
  finner. Men skikkelsen er bevisstløs.
+ Med skikkelsen om bord skifter fokuset over til å unnslippe en
  malstrøm som har etablert seg i området. Kontessa fiker til de
  nysgjerrige rekruttene, og roper om at de må ro hardt for å komme i
  land.
+ Med ett slår et lyn ned i båten, og mannskapet på båten blir
  momentant slått ut og våkner opp igjen på dekk. Båten er permanent
  skadet, og driver inn mot en naturlig molo. Idet den kolliderer,
  faller mannskapet ut i vannet.
+ De får fiskeskapningen ved bevissthet, men den bryter ut i panikk og
  roper at den må komme seg vekk fra øya. «Jeg må vekk, ingen er
  trygge!». Han sier han heter Yutsa.
+ Dania og Elrika finner ut at Yutsa og hennes folk - Kolrathi -
  tydeligvis er korrumpert som følge av et rituale.
+ Maleksei Spør Yutsa om hun vet hvem Deikart Pober er, og det kommer
  til et punkt hvor Elrika prøver å overtale Yutsa til å fortelle dem
  alt hun vet.
+ Yutsa forklarer at de er ikke lenger alene i vannet. Vanligvis gjør
  de et rituale på det dype havet, men de er tvunget på
  vandring. Deikart ba dem holde rituale hos ham, i hans palass.
+ Videre har det seg slik at Yutsa skulle bringe mørket, eller
  forbandelsen vekk fra folket hennes. Da følget helbredet henne, ble
  mørket således slippet løs.
+ De bestemmer seg for å ta med Yutsa opp til Deikart Pobert.
+ På veien opp til palasset går de langs en tett inngrodd sti, med
  tydelig giftige planter og vekst som dekker veien. Palasset, når de
  kommer fram, ser ut til å være blodrødt, dekket til av illevarslende
  vegetasjon. Inne i palasset er det masse mat som står dekket til, og
  videre innover ser de en gammel mann som sitter i en stol. Bak han
  er det et maleri av Voyis.
+ Contessa og Deikart snakker om hva Legionen trenger, men Maleksei
  tråkker brått frem og går ned på sine knær. Contessa har ikke klart
  å vise den desperate posisjonen til Legionen, mener han, og ber
  Deikart om å vise generøs.
+ Contessa drar fram et sverd av gull, og tilbyr det i bytte mot hjelp
  fra Deikart. De begynner å forhandle, men Deikart virker ikke
  overbevist. «Jeg ville ha overbevisning. Noe som kom innenifra. Ikke
  billige triks. Alle kan gjøre en blodsed, ikke alle kan se dypt inne
  i seg. Kanskje Legionen ikke er tilstrekkelig allikevel».
+ Dania tilbyr seg å hjelpe, og Deikart godtar i bytte mot en slags
  forbandelse over Dania. Men ide korrupsjonen skal tre inn i synger
  hun mens hun holder for brystet -- hun klarer å stå i mot!
+ Deikart er tydelig imponert, og ser på gjengen som står framfor
  ham. «Det er fortsatt styrke og ære i Legionen. Kanskje verden ikke
  er tapt likevel. Mine lagre er åpne for dere. Til gjengeld, når dere
  hører havets røst, da er Legionen bundet til å svare.»
